### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by the4ndy** [DragonLegend/game#46]
I am creating a fresh droplet on DigitalOcean with the MEAN stack image. Node version is 0.12.1 I git clone this repo and then npm install and get no errors. on npm start i get the following output....sorry if i am being dumb and doing something wrong :/

root@DevBox-0:/var/www/game# npm start

> game@0.2.0 start /var/www/game
> gulp start

[17:45:44] Using gulpfile /var/www/game/gulpfile.js
[17:45:44] Starting 'start'...
[17:45:44] Finished 'start' after 1.91 ms
[17:45:44] [nodemon] v1.3.7
[17:45:44] [nodemon] to restart at any time, enter `rs`
[17:45:44] [nodemon] ignoring: public/**/* node_modules/**/*
[17:45:44] [nodemon] watching: *.js *.png
[17:45:44] [nodemon] watching extensions: js
[17:45:44] [nodemon] bind crash -> `osascript -e 'display notification "Game app crashed" with title "nodemon"'`
[17:45:44] [nodemon] starting `DEBUG='game:*' babel-node --harmony --debug app.js`
[17:45:44] [nodemon] child pid: 2285
sh: 1: babel-node: not found
[17:45:44] [nodemon] failed to start process, "DEBUG='game:*' babel-node --harmony --debug" exec not found
[17:45:44] [nodemon] exiting
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at emit (events.js:87:13)
    at ChildProcess.<anonymous> (/var/www/game/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/run.js:119:11)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1067:12)

npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! game@0.2.0 start: `gulp start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the game@0.2.0 start script 'gulp start'.
npm ERR! This is most likely a problem with the game package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp start
npm ERR! You can get their info via:
npm ERR!     npm owner ls game
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/game/npm-debug.log

**Comment by ButuzGOL** [comment]
I do update 'usage' part
If you have any questions please ask

**Comment by ButuzGOL** [comment]
New structure
